services:
  # API Rest do Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: harpia_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    command: php artisan serve --host=0.0.0.0 --port=8000
    networks:
      - harpia_network

  # Worker de Filas para o Processamento Concorrente
  queue:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: harpia_queue
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    # Aumentado o timeout para 300 para suportar o tempo de resposta das IAs
    # command: php artisan queue:work --tries=3 --timeout=300 (Production)
    command: php artisan queue:work --queue=mining --tries=3 --timeout=300
    depends_on:
      - backend
    networks:
      - harpia_network

  # Dashboard Angular
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: harpia_frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Impede que os m√≥dulos locais sobrescrevam os do container
    command: npm start -- --host 0.0.0.0
    networks:
      - harpia_network

networks:
  harpia_network:
    driver: bridge
